### ISSUE TITLE
Sunbird UCI Documentation Related Changes List | V2

### ISSUE THREAD

**Issue by pankajjangid05** [samagra-comms/community#29]
**Need to Change**

- [ ] Update to v2 APIs
          1. [Setting up your very first conversation](https://uci.sunbird.org/use/adopter/setting-up-your-very-first-conversation)
          2. [Firebase Notification Adapter](https://uci.sunbird.org/use/developer/uci-basics/adapters/firebase-notification-adapter)
          3. [Bot Setup Apis](https://uci.sunbird.org/use/developer/api-documentation/bot-setup-apis)
          4. [History Api](https://uci.sunbird.org/use/developer/api-documentation/history-apis)
          5. [Direct Message Send Apis](https://uci.sunbird.org/use/developer/api-documentation/direct-message-apis) Need to change URLs.
          6.  [Link](https://uci.sunbird.org/use/developer/api-documentation/vault-apis#2.2-add-secret-credentials-api) Need to change the URL of save credentials in the vault.
- [ ] Link not working | URL Change
          1. [Sample ODK Excel Form](https://uci.sunbird.org/use/adopter/setting-up-your-very-first-conversation#1.1.-uci-admin)
          2. [firebase details of UCI](https://uci.sunbird.org/use/developer/uci-basics/adapters/firebase-notification-adapter#1.-use-uci-internal-apis)
          3. [page](https://uci.sunbird.org/use/developer/uci-basics/adapters/firebase-notification-adapter) The tokens registered can be fetched via the [API](http://143.110.255.220:8080/fusionAuth/fetchFcmTokens)
          4. [page](https://uci.sunbird.org/use/developer/uci-basics/adapters/firebase-notification-adapter) Create a new service [here](http://143.110.255.220:15003/console/data/default/schema/public/tables/service/browse) with the fetch token API in config.
          5. [page](https://uci.sunbird.org/use/developer/uci-basics/adapters/firebase-notification-adapter) Create a new user segment [here](http://143.110.255.220:15003/console/data/default/schema/public/tables/userSegment/browse) with the service created in step 3. Or you can use an already created user segment for this case. cf085492-266f-46d1-841c-1b38e93bce3f.
          6. [page](https://uci.sunbird.org/use/developer/uci-basics/adapters/firebase-notification-adapter) Create a new service [here](http://143.110.255.220:15003/console/data/default/schema/public/tables/service/browse) with the your token API.
          7. [page](https://uci.sunbird.org/use/developer/uci-basics/adapters/firebase-notification-adapter) Create a new user segment [here](http://143.110.255.220:15003/console/data/default/schema/public/tables/userSegment/browse) with the service created in step 4.
          8. [page](https://uci.sunbird.org/use/developer/development-environment/backend-setup#4.-setup) Add [Enviorment Variable](https://github.com/orgs/samagra-comms/projects/2/views/2?pane=issue&itemId=26041801) in IDE.
          9. [page](https://uci.sunbird.org/use/developer/development-environment/environment-variable-setup) VAULT_SERVICE_URL=http://143.110.183.73:3001
- [ ] Need to check broadcast-transformer configuration and verify if is it according to v2 configuration or not [link](https://uci.sunbird.org/use/developer/uci-basics/transformers/broadcast-transformer)
- [ ] Need to change existing implementation code URLs with the latest branch code
          1.  [Adapter](https://uci.sunbird.org/use/developer/contribution-guide/create-an-adapter#7.-list-of-existing-adapter-implementations)
          2. [Converter](https://uci.sunbird.org/use/developer/contribution-guide/adapter-implementation#2.3-existing-implementations)
          3. [Outbound Implementation](https://uci.sunbird.org/use/developer/contribution-guide/adapter-implementation#3.-outbound-implementation)
- [ ] Change to the latest branch [link](https://uci.sunbird.org/use/developer/contribution-guide/adapter-implementation#2.1-setup-inbound)

**Need to Discuss**

- [ ] All the API's URLs should be on a single URL Exp :  
        1. Doc Sample URL 1: http://localhost:9999/admin/v1/forms/upload
        2. Doc Sample URL 2: http://143.110.255.220:9090/message/send
- [ ] Media Upload API-related changes in ODK Form API
- [ ] Should we add conversation history API in the document?

**Docker deploy related changes** 

- [ ] Some new changes were added in the docker deploy repository by Tushar, so we need to check this document and verify all steps are right or need some changes [link](https://uci.sunbird.org/use/adopter/pre-requisites-installation-setup-post-setup)

**Comment by karntrehan** [comment]
* Update [Setting up your very first conversation](https://uci.sunbird.org/use/adopter/setting-up-your-very-first-conversation) with new install steps.
* Does `Setting up your very first conversation` really work? What about orgId, adapterId and transformerId? Do we prepack a few elements already? 
* What about environment variables for admin panel? Does that need to be updated as well? 
* UCI Basics - Add a diagram to show how the various elements work together. 

> Should we add conversation history API in the document?
Yes. We should atleast start with all of them which were covered in NL chatbot.

> All the API's URLs should be on a single URL Exp :
All should be localhost as the assumption is people have already deployed locally using docker.

**Comment by geeky-abhishek** [comment]
@karntrehan to review

**Comment by chinmoy12c** [comment]
Planning is done, we'll break this into smaller tickets. Moving to done.

**Comment by susheelvar** [comment]
@chinmoy12c to break into sub-tickets.
