### ISSUE TITLE
[Docs] Update documentation of bot setup api to match v2

### ISSUE THREAD

**Issue by chinmoy12c** [samagra-comms/community#36]
The bot setup API documentation here: https://uci.sunbird.org/use/developer/api-documentation/bot-setup-apis needs to be updated to match the changes in v2.

**Comment by karntrehan** [comment]
Reviewed by @karntrehan

**Comment by karntrehan** [comment]
@geeky-abhishek @RyanWalker277 and @karntrehan to sync on end use case to be developed.
