### ISSUE TITLE
[Doc] NL Bot Management

### ISSUE THREAD

**Issue by susheelvar** [samagra-comms/community#46]
Link to Document - https://docs.google.com/document/d/1JKJijTa0vnyJ-Nsk-HNAckG-MFMJqhJQl59Fd9Mj-qM/edit

**Comment by karntrehan** [comment]
Use this: https://docs.google.com/document/d/12C3j2t7HSK4pH0kOyWuP9V_8taZmGTPsQn0esrTJCeI/edit
