### ISSUE TITLE
Whatsapp / SMS testing

### ISSUE THREAD

**Issue by geeky-abhishek** [samagra-comms/community#61]
We have been building the FCM funnel and testing the same. We need to spend some time on testing the Whatsapp and SMS flows as well to ensure we are in place there as well.

**Comment by pankajjangid05** [comment]
Whatsapp Bot Conversation Testing 

- [ ] Netcore Service
- [ ] Gupshup Service

Sending SMS Testing

- [ ] CDAC Service

**Comment by chinmoy12c** [comment]
Tested, Netcore + WhatsApp, CDAC + SMS, GUPSHUP + SMS, working fine.
Gupshup + Whatsapp has some errors. Need to be debugged.

**Comment by pankajjangid05** [comment]
Working on below points : 

Gupshup SMS

- [ ] Gupshup SMS end-to-end testing with create a new broadcast bot
- [ ] Gupshup SMS working flow diagram update [URL](https://app.diagrams.net/#G1pq3ZdEic8ZvPuJlM50EWpGjZ1OQz1ZGY)
- [ ] Gupshup SMS documentation

CDAC SMS

- [ ] CDAC SMS end-to-end testing with create a new broadcast bot
- [ ] CDAC SMS working flow diagram update [URL](https://app.diagrams.net/#G1pq3ZdEic8ZvPuJlM50EWpGjZ1OQz1ZGY)
- [ ] CDAC SMS documentation

**Comment by karntrehan** [comment]
Documentation and flow diagrams to be completed today.

**Comment by pankajjangid05** [comment]
Hey @chinmoy12c 

I modified the logic to execute the SMS end-to-end flow. Please review these PRs : 

[Broadcast-Transformer](https://github.com/samagra-comms/broadcast-transformer/pull/27)
[Orchestrator](https://github.com/samagra-comms/orchestrator/pull/66)

**Comment by karntrehan** [comment]
@pankajjangid05 to share a table of what steps are required in each trigger flow: 
* SMS
* Broadcast Whatsapp
* Bot Whatsapp
* FCM embedded bot
* others. 

Netcore Whatsapp demo to be undertaken and documentation to be picked up. 

@RyanWalker277 to start contributing to this as well.

**Comment by aakashyadav-kgp** [comment]
@pankajjangid05 will share the sheet here and @RyanWalker277

**Comment by RyanWalker277** [comment]
To be picked up on wednesday by @RyanWalker277

**Comment by geeky-abhishek** [comment]
@RyanWalker277 will pick this today

**Comment by geeky-abhishek** [comment]
@RyanWalker277 need to test/demo the whatsapp flow

**Comment by geeky-abhishek** [comment]
@RyanWalker277 will schedule a demo today

**Comment by karntrehan** [comment]
Demo undertaken.

* Whitelisting to be understood. 
* Documentation & postman collection to be updated. 

@geeky-abhishek and @karntrehan to work on the updates needed on web channel.

**Comment by RyanWalker277** [comment]
Sharing the documentation and upated collection links here.

- [Documentation](https://docs.google.com/document/d/1pvXicy86KJPItcDzjRXpk3kFncBpmOG6wA64UKHN6nQ/edit?usp=sharing)
- [Updated Collection](https://making-impact-at-scale.postman.co/workspace/Team-Workspace~0829531a-4751-4222-858f-d76774ea3c96/folder/19777315-d573b21c-3e4e-4950-a3a5-625a831fb96c?ctx=documentation)

**Comment by RyanWalker277** [comment]
Sharing the documentation and upated collection links here.

- [Documentation](https://docs.google.com/document/d/1pvXicy86KJPItcDzjRXpk3kFncBpmOG6wA64UKHN6nQ/edit?usp=sharing)
- [Updated Collection](https://making-impact-at-scale.postman.co/workspace/Team-Workspace~0829531a-4751-4222-858f-d76774ea3c96/folder/19777315-d573b21c-3e4e-4950-a3a5-625a831fb96c?ctx=documentation)

**Comment by karntrehan** [comment]
@chinmoy12c to review documentation and push to UCI doc repo.

**Comment by RyanWalker277** [comment]
PR Link : https://github.com/samagra-comms/community/pull/64

**Comment by geeky-abhishek** [comment]
@RyanWalker277 to work on PR feedbacks.

**Comment by pankajjangid05** [comment]
Hey @RyanWalker277 

Please check this API and explore it : https://cpaasdocs.netcorecloud.com/docs/whatsappapidoc/2855d2c350ac3-blocklist-whitelist

**Comment by karntrehan** [comment]
Whitelisting to be done by Gupshup & Netcore.

**Comment by aakashyadav-kgp** [comment]
WIP

**Comment by chinmoy12c** [comment]
Received response from Gupshup, need to provide them with updated hooks.

**Comment by aakashyadav-kgp** [comment]
Modified endpoints sent to gupshup. Awaiting confirmation. Will test changes once we get confirmation.

**Comment by chinmoy12c** [comment]
Received updated webhooks from Gupshup. To be tested tomorrow.

**Comment by karntrehan** [comment]
On Gupshup: we have updated the webhooks. We are getting requests, responses are not being sent from Gupshup. To be raised today. 

On netcore: Flow is working fine.

**Comment by karntrehan** [comment]
Drop Gupshup. We will support only netcore.

**Comment by RyanWalker277** [comment]
PR Link: https://github.com/samagra-comms/community/pull/76
