### ISSUE TITLE
[Release Note] Send out release note for a major release

### ISSUE THREAD

**Issue by karntrehan** [samagra-comms/community#69]
We should send out a release note for all the major changes we have done to UCI.

**Comment by karntrehan** [comment]
This should be a release from the community page which has an overall update. With releases from each layer with layer specific information of the releases. 

We should talk about the scale we have reached in the release with performances.

**Comment by karntrehan** [comment]
We should also send a post from linkedin for the latest major release.

**Comment by chinmoy12c** [comment]
Release note added here:
https://uci.sunbird.org/releases/release_v2
