### ISSUE TITLE
Finalise source of truth for notification numbers

### ISSUE THREAD

**Issue by karntrehan** [samagra-comms/community#73]
We currently have numbers from: 
* Firebase
* Posthog
* Cassandra
* UCI telemetry

We should finalise which is the correct method to calculate this.

**Comment by aakashyadav-kgp** [comment]
Planning to close this out today. Firebase and Cassandra seems more accurate. Figuring out why Posthog data is off.

**Comment by karntrehan** [comment]
Doc: https://docs.google.com/spreadsheets/d/1zNfbwNKe8-qR_JYcLn1zVF_Vt53P5656bW1jPPCTO9I/edit#gid=0
